---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave
spec:
  selector:
    matchLabels:
      app: slave
  template:
    metadata:
      labels:
        app: slave

    spec:
      containers:
      - name: slave
        image: mfadel8/slave1:final
        imagePullPolicy: Never
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: "/var/run/docker.sock"
          name: host-mount

      volumes:
      - name: host-mount
        hostPath:
          path: "/var/run/docker.sock"

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-slave-service
spec:
  # type: LoadBalancer
  selector: 
    app: slave
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
